#!/bin/bash
directory=$(pwd)

prefix=/home/$USER/Drupal8-vagrant/web

container_root=/var/www/html

suffix=${directory#"$prefix"}

dockerpath=$container_root$suffix

if [ $suffix = $directory ];
then
    docker exec -it drupal8-vagrant_drupal_1 bash
else
    docker exec -it drupal8-vagrant_drupal_1 bash -c 'cd '$dockerpath'; exec "${SHELL:-sh}"'
fi
